name: Update Files from API

on:
  repository_dispatch:
    types: [update-files]

jobs:
  update-files:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Create Branch
        run: |
          BRANCH_NAME="update-files-$(date +%Y%m%d-%H%M%S)"
          git checkout -b $BRANCH_NAME
          echo "BRANCH_NAME=$BRANCH_NAME" >> $GITHUB_ENV

      - name: Download ZIP from API
        run: |
          curl -o files.zip "https://translator.cnr.stijnjw.com/api/translations/retrieve/xml"

      - name: Unzip Files
        run: |
          unzip -o files.zip -d new_files

      - name: Move Files to Repository
        run: |
          mv new_files/* .

      - name: Commit and Push Changes
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add --all
          git diff --cached --quiet || git commit -m "Update files from API"
          git push origin $BRANCH_NAME

      # - name: Create Pull Request
      #   uses: peter-evans/create-pull-request@v6
      #   with:
      #     branch: ${{ env.BRANCH_NAME }}
      #     base: main
      #     title: "Automated File Update"
      #     body: "This PR contains updated files from the API."
      #     labels: "automation, api-update"
